### ISSUE TITLE
Can't reach markets for update error

### ISSUE THREAD

**Issue by bdmeyer** [PoC-Consortium/burstcoin-mobile-doc#41] opened 2018-04-01 13:59 UTC
If you have multiple feature requests, please create a seperate issue for each individual feature.
If you report a bug, please use the following template!

**Specifications**

  - Application Version: 0.2.1
  - Android Version: 8.1.0
  - Device: Pixel

**Expected Behavior**
On Balance tab, .market value is displayed at bottom. For updated market value swipe down and it will update.

**Actual Behavior & Screenshots**
When app loads, no market value is displayed. Swipe down, refresh runs for about 8 seconds and displays error that ' Could not reach market for currency updates, check internet connection'
**Steps to Reproduce the Problem**

  1. Load app
  2. Wait for Blue text to turn black. If no market value, swipe down. 
  3. Internet connection is fine. Have rebooted many time in past 10 days since I first noticed this. Initially thought it was a hotel paywall related issue. Am at home now and issue persists.

**Comment by cgebe** [comment] 2018-04-02 09:45
The API of coinmarketcap did not change, therefore the market update fetch should work as intended. Maybe your IP was blocked by CMC. We are looking into adding alternative sources for market updates.

**Comment by bdmeyer** [comment] 2018-04-02 10:07
Thanks for the feedback Chris. I notice on occasion I get the market update. More often than not, no. I think this started shortly after the 13th of March, but I can't say which day.  Thanks for the great app.


--Bruce D. Meyer


________________________________

**Comment by cgebe** [comment] 2018-06-21 09:42
Close this as resolved, due to doc repo movement

**Closed by cgebe** 2018-06-21 09:42 UTC
